### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by brunocalado** [mhilbrunner/token-hud-wildcard#4]
Hi. I can't get the module to work. 

I set to `worlds/last-days-of-anglekite/tokenizer/pcs/wendy/tokens/*`
![image](https://github.com/user-attachments/assets/79a718a2-b042-489b-b94a-0f475696632b)
![image](https://github.com/user-attachments/assets/b8deb886-a5ae-4920-8b01-85051c8b3dce)

There is an error on world load:
foundry.js:27993 Error: Invalid Asset worlds/last-days-of-anglekite/tokenizer/pcs/wendy/tokens/*
    at loadTexture (foundry.js:27986:40)
    at async TokenPbta._draw (foundry.js:59390:20)
    at async foundry.js:26571:7
    at async Promise.all (index 0)
    at async TokenLayer._draw (foundry.js:34167:5)
    at async TokenLayer._draw (foundry.js:41429:5)
    at async foundry.js:33579:7
    at async InterfaceCanvasGroup._draw (foundry.js:28123:9)
    at async InterfaceCanvasGroup._draw (foundry.js:50498:5)
    at async foundry.js:28107:9
    at async #draw (foundry.js:24912:9)
    at async Canvas.draw (foundry.js:24798:5)
    at async Scene.view (foundry.js:21268:7)
    at async Game.initializeCanvas (foundry.js:9193:20)
    at async Game.setupGame (foundry.js:9017:5)
    at async Game._initializeGameView (foundry.js:10354:5)
    at async Game.initialize (foundry.js:8917:5)

**Comment by mhilbrunner** [comment]
You need to check the option "Use ranomized/wildcard image", the first checkbox (second option below the URL at the top).
